project_id = "ejfjvdtbqduvvbjpgrrm"

[auth]
enabled = true
site_url = "https://lovable.dev"

[functions.rag-chat]
verify_jwt = true

[functions.process-document]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = true

[functions.chat-search]
verify_jwt = false
